In [ ]:
#importing
import numpy as np

In [ ]:
#Creating 1D array
A = np.array([2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#Creating 2D array
B = np.array([[2,3,4],[7,8,9]])
print(B)

[[2 3 4]
 [7 8 9]]


In [ ]:
#Creating 3D array - rows,columns,groups
C = np.array([[[2,3,4],[6,7,8]],[[6,9,0],[2,3,1]]])
print(C)

[[[2 3 4]
  [6 7 8]]

 [[6 9 0]
  [2 3 1]]]


In [ ]:
#Checking dimensions of array
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
#Ones
D = np.ones((2,3))  #rows,columns,2D
print(D)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Ones
E = np.ones((2,3,3))   #groups,rows,columns,3D
print(E)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#Zeroes
F = np.zeros(2)
print(F)

[0. 0.]


In [ ]:
#Eye
G = np.eye(4)
print(G)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Arange
H = np.arange(3,31,3)
print(H)

[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
#Reshape
H = np.arange(3,31,3).reshape(5,2)
print(H)

[[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]


In [ ]:
#Printing 5 table using arange function
I = np.arange(5,1001,5).reshape(10,20)
print(I)

[[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
    75   80   85   90   95  100]
 [ 105  110  115  120  125  130  135  140  145  150  155  160  165  170
   175  180  185  190  195  200]
 [ 205  210  215  220  225  230  235  240  245  250  255  260  265  270
   275  280  285  290  295  300]
 [ 305  310  315  320  325  330  335  340  345  350  355  360  365  370
   375  380  385  390  395  400]
 [ 405  410  415  420  425  430  435  440  445  450  455  460  465  470
   475  480  485  490  495  500]
 [ 505  510  515  520  525  530  535  540  545  550  555  560  565  570
   575  580  585  590  595  600]
 [ 605  610  615  620  625  630  635  640  645  650  655  660  665  670
   675  680  685  690  695  700]
 [ 705  710  715  720  725  730  735  740  745  750  755  760  765  770
   775  780  785  790  795  800]
 [ 805  810  815  820  825  830  835  840  845  850  855  860  865  870
   875  880  885  890  895  900]
 [ 905  910  915  920  925  930  935  940  945  950  95

In [ ]:
#Linspace
J = np.linspace(12,24,10)
print(J)

[12.         13.33333333 14.66666667 16.         17.33333333 18.66666667
 20.         21.33333333 22.66666667 24.        ]


In [ ]:
K = np.arange(1,7).reshape(2,3)
print(K)
L = np.arange(9,15).reshape(2,3)
print(L)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [ ]:
#Addition of arrays
print(K+L)

[[10 12 14]
 [16 18 20]]


In [ ]:
#Addition of all elements of array obtained by addition of arrays
M = np.sum((K,L))
print(M)

90


In [ ]:
#Addition of arrays along columns
M = np.sum((K,L),axis=0)
print(M)

[[10 12 14]
 [16 18 20]]


In [ ]:
#Addition of arrays along rows
M = np.sum((K,L),axis=1)
print(M)

[[ 5  7  9]
 [21 23 25]]


In [ ]:
#Addition of arrays along groups
M = np.sum((K,L),axis=2)
print(M)

[[ 6 15]
 [30 39]]


In [ ]:
N = np.ones((4,2))
O = np.ones((4,2))
P=(np.sum((N,O),axis=1))
print(P)

[[4. 4.]
 [4. 4.]]


In [ ]:
#Multiplication of arrays
Q = np.array([[1,1],[0,1]])
R = np.array([[2,0],[3,4]])
S=Q*R
print(S)

[[2 0]
 [0 4]]


In [ ]:
#Square roots of elements os an array
T = np.array([25,289,361,81])
for i in T:
  print(np.sqrt(i),"square is ",i)

5.0 square is  25
17.0 square is  289
19.0 square is  361
9.0 square is  81


In [ ]:
U = np.array([25,289,361,81])
V = np.sqrt(U)
W = zip(V,U)
for i in W :
  print(i)

(5.0, 25)
(17.0, 289)
(19.0, 361)
(9.0, 81)


In [ ]:
a = np.array([34,35,36,37,38,39])
a.resize(2,3)
b = np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))        #columns
print("\n")
print(np.hstack((a,b)))        #rows


[[34 35 36]
 [37 38 39]
 [ 4  5  6]
 [ 7  8  9]]


[[34 35 36  4  5  6]
 [37 38 39  7  8  9]]
