In [ ]:
import numpy as np

In [ ]:
a = np.ones((8,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY
#rand - range is between zero(0) and one(1)
b=np.random.rand(8,4)
print(b)

[[0.87683027 0.93930769 0.69508194 0.86946851]
 [0.15566522 0.42987187 0.89264927 0.09351969]
 [0.62714128 0.14932917 0.58464776 0.77758043]
 [0.42449688 0.67734315 0.01213737 0.57451473]
 [0.36006716 0.84752918 0.90236634 0.68467689]
 [0.36900714 0.63509468 0.20026221 0.89843572]
 [0.12290943 0.75327268 0.96833128 0.33022469]
 [0.09002533 0.56961185 0.17985853 0.16702423]]


In [ ]:
c=np.arange(1,33).reshape(8,4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
#Vsplit
np.vsplit(c,4)       #splits into required number of parts vertically

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
# splitting at required positions
np.vsplit(c,(2,6))     #splits at 2 and 6(from starting) and remaining

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
d=np.arange(1,33).reshape(4,8)
print(d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
#Hsplit
np.hsplit(d,4)         #splits into required number of parts  horizontally

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
#Hsplit
np.hsplit(d,(2,6))               #splits first 2 columns and 6 columns(from starting) and remaininig

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5,  6],
        [11, 12, 13, 14],
        [19, 20, 21, 22],
        [27, 28, 29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

Trigonometry

In [ ]:
#PI value
np.pi

3.141592653589793

In [ ]:
e=np.pi
f=[e/4,e/3,e/2,e]
print(f)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
#Radian to Degree conversion
g=np.rad2deg(f)
print(g)

[ 45.  60.  90. 180.]


In [ ]:
#Degree to Radian conversion
h=np.deg2rad(g)
print(h)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
#Sin value
np.sin(1)

0.8414709848078965

In [ ]:
#Cos value
np.cos(1)

0.5403023058681398

In [ ]:
#Tan value
np.tan(1)

1.5574077246549023

Statistics

In [ ]:
i = np.array([23,45,67,89,21,34])

In [ ]:
#Mean
np.mean(i)

46.5

In [ ]:
#Median
np.median(i)

39.5

In [ ]:
#Standard deviation
np.std(i)

24.452334585202017

In [ ]:
#Variance
np.var(i)

597.9166666666666

In [ ]:
j=np.arange(1,5).reshape(2,2)
print(j)

[[1 2]
 [3 4]]


In [ ]:
#Inverse of matrix
np.linalg.inv(j)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
k=np.arange(1,21).reshape(5,4)
print(k)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
#Index of maximum value
np.argmax(k)      #Gives index of maximum value(index starts from zero.so,max value 20 is present at 19 index position)

19

In [ ]:
l=10*np.random.rand(20).reshape(5,4)
print(l)

[[7.88947307 6.65321726 9.93834196 2.12710714]
 [3.88560625 3.87232913 5.77235418 2.55813231]
 [3.34844727 2.9639871  6.31232356 1.39253985]
 [6.20857567 9.30515039 5.54434378 8.28913099]
 [4.44502036 9.63036154 0.16987032 8.88329486]]


In [ ]:
np.argmax(l)           #Gives index of max value of matrix

2

In [ ]:
np.argmax(l,axis=0)     #Gives index of max value along columns

array([0, 4, 0, 4])

In [ ]:
np.argmax(l,axis=1)      #Gives index of max value along rows

array([2, 2, 2, 1, 1])

In [ ]:
np.argmin(l)             #Gives index of min value of matrix

18

In [ ]:
np.argmin(l,axis=0)       #Gives index of min value along columns

array([2, 2, 4, 2])

In [ ]:
np.argmin(l,axis=1)        #Gives index of min value along rows

array([3, 3, 3, 2, 2])

Searching

In [ ]:
m = np.array([34,56,7,17,88,91])
print(np.where(m%2 == 0))             #Gives index of even values

(array([0, 1, 4]),)


In [ ]:
print(np.where(m%2!=0))               #Gives index of odd values

(array([2, 3, 5]),)


In [ ]:
#Searches only in a sorted list
n=np.array([1,2,3,4,5])
np.searchsorted(n,5)                   #Gives index of required value

4

Sorting

In [ ]:
o=np.array(['balu','vamc','ashok'])
print(np.sort(o))

['ashok' 'balu' 'vamc']


In [ ]:
p=np.array([True,False,True])
print(np.sort(p))

[False  True  True]


In [ ]:
q=np.array([45,18,63,7,1])
np.sort(q)

array([ 1,  7, 18, 45, 63])

In [ ]:
#2D - sort
r=np.array([[6,2,4],[7,3,5]])                     #Sorts along rows
np.sort(r)

array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
#Filter
s=np.array([40,15,60,25,74])
filt=np.where(s%2==0)                       #Gives index of required values(here even values)
print(filt)

(array([0, 2, 4]),)


In [ ]:
s[filt]                                     #Gives values  for indexes

array([40, 60, 74])

In [ ]:
#Traversing two arrays at a time
u=np.array(["Balu","Gana","Rishi"])
v=np.array(["P","G","T"])
for i,j in zip(u,v) :
  print(j,".",i)

P . Balu
G . Gana
T . Rishi


In [ ]:
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,22,23,24,25])
np.multiply(a,b)

array([ 200,  420,  660,  920, 1200, 1500])

In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
np.divide(a,b)

array([ 0.5,  1. , 15. ,  2. ,  2. ,  2.4])

In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
np.mod(a,b)

array([10,  0,  0,  0,  0, 10])

In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([3,2,2,7,10,7])
np.divmod(a,b)

(array([ 3, 10, 15,  5,  5,  8]), array([1, 1, 0, 5, 0, 4]))

Logarithms

In [ ]:
np.log(1.2)                   #Natural log e

0.1823215567939546

In [ ]:
a=np.array([1,2,3,4,])
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.log2(1.2)                  #log base 2

0.2630344058337938

In [ ]:
np.log10(1.2)                 #log base 10

0.07918124604762482

Other mathematical functions

In [ ]:
#Cumulative product
b=np.array([5,6,7,10])              #Gives multiplication of two values(5,5*6=30,30*7=210)
np.cumprod(b)

array([   5,   30,  210, 2100])

In [ ]:
#Cumulative sum
np.cumsum(b)                        #Gives sum of two values (5,5+6=11,11+7=18)

array([ 5, 11, 18, 28])

In [ ]:
#Difference
c=np.array([10,15,25,15])           #Gives differrence between two values(15-10=5,25-15=10)
np.diff(c)

array([  5,  10, -10])

In [ ]:
#LCM
np.lcm(16,24)

48

In [ ]:
#LCM of an array
a=np.array([4,8,16,24])
np.lcm.reduce(a)

48

In [ ]:
#GCD
np.gcd(16,24)

8

In [ ]:
#GCD of an array
a=np.array([4,8,16,24])
np.gcd.reduce(a)

4